# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, param world! 
  displayName: 'Run a one-line script'

- task: SynopsysPolaris@1
  inputs:
    polarisService: 'test01'
    polarisCommand: 'polaris'
    waitForIssues: true
    populateChangeSetFile: true

- task: BlackduckCoverityOnPolaris@2
  inputs:
    polarisService: 'test1'
    polarisCommand: 'polaris'
    waitForIssues: true
    populateChangeSetFile: true

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
